# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'resources/file_upload_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MenuFileUploadDig(object):
    def setupUi(self, MenuFileUploadDig):
        MenuFileUploadDig.setObjectName("MenuFileUploadDig")
        MenuFileUploadDig.resize(750, 131)
        self.gridLayout = QtWidgets.QGridLayout(MenuFileUploadDig)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(MenuFileUploadDig)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(MenuFileUploadDig)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.textEdit = QtWidgets.QTextEdit(MenuFileUploadDig)
        self.textEdit.setMaximumSize(QtCore.QSize(16777215, 25))
        self.textEdit.setObjectName("textEdit")
        self.gridLayout.addWidget(self.textEdit, 0, 1, 1, 1)
        self.pushButton = QtWidgets.QPushButton(MenuFileUploadDig)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 0, 3, 1, 1)
        self.textEdit_2 = QtWidgets.QTextEdit(MenuFileUploadDig)
        self.textEdit_2.setMaximumSize(QtCore.QSize(16777215, 25))
        self.textEdit_2.setObjectName("textEdit_2")
        self.gridLayout.addWidget(self.textEdit_2, 1, 1, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(MenuFileUploadDig)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 2, 1, 1, 1)

        self.retranslateUi(MenuFileUploadDig)
        QtCore.QMetaObject.connectSlotsByName(MenuFileUploadDig)

    def retranslateUi(self, MenuFileUploadDig):
        _translate = QtCore.QCoreApplication.translate
        MenuFileUploadDig.setWindowTitle(_translate("MenuFileUploadDig", "Dialog"))
        self.label_2.setText(_translate("MenuFileUploadDig", "Cloud directory"))
        self.label.setText(_translate("MenuFileUploadDig", "Local directory"))
        self.pushButton.setText(_translate("MenuFileUploadDig", "Browse"))
        self.pushButton_2.setText(_translate("MenuFileUploadDig", "upload"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MenuFileUploadDig = QtWidgets.QDialog()
    ui = Ui_MenuFileUploadDig()
    ui.setupUi(MenuFileUploadDig)
    MenuFileUploadDig.show()
    sys.exit(app.exec_())
