# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'resources/file_opencloud_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MenuFileOpenCloudDig(object):
    def setupUi(self, MenuFileOpenCloudDig):
        MenuFileOpenCloudDig.setObjectName("MenuFileOpenCloudDig")
        MenuFileOpenCloudDig.resize(592, 554)
        self.gridLayout = QtWidgets.QGridLayout(MenuFileOpenCloudDig)
        self.gridLayout.setObjectName("gridLayout")
        self.treeView = QtWidgets.QTreeView(MenuFileOpenCloudDig)
        self.treeView.setEditTriggers(QtWidgets.QAbstractItemView.EditKeyPressed)
        self.treeView.setSortingEnabled(True)
        self.treeView.setObjectName("treeView")
        self.gridLayout.addWidget(self.treeView, 0, 2, 1, 1)
        self.widget = QtWidgets.QWidget(MenuFileOpenCloudDig)
        self.widget.setMinimumSize(QtCore.QSize(0, 25))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.gridLayout.addWidget(self.widget, 4, 2, 1, 1, QtCore.Qt.AlignRight)
        self.widget_2 = QtWidgets.QWidget(MenuFileOpenCloudDig)
        self.widget_2.setMinimumSize(QtCore.QSize(0, 0))
        self.widget_2.setMaximumSize(QtCore.QSize(16777215, 50))
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.widget_2)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.textEdit = QtWidgets.QTextEdit(self.widget_2)
        self.textEdit.setMaximumSize(QtCore.QSize(16777215, 25))
        self.textEdit.setObjectName("textEdit")
        self.horizontalLayout_2.addWidget(self.textEdit)
        self.pushButton_3 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_2.addWidget(self.pushButton_3)
        self.gridLayout.addWidget(self.widget_2, 3, 2, 1, 1)

        self.retranslateUi(MenuFileOpenCloudDig)
        QtCore.QMetaObject.connectSlotsByName(MenuFileOpenCloudDig)

    def retranslateUi(self, MenuFileOpenCloudDig):
        _translate = QtCore.QCoreApplication.translate
        MenuFileOpenCloudDig.setWindowTitle(
            _translate("MenuFileOpenCloudDig", "Dialog")
        )
        self.pushButton.setText(_translate("MenuFileOpenCloudDig", "Open"))
        self.pushButton_2.setText(_translate("MenuFileOpenCloudDig", "Cancel"))
        self.label.setText(_translate("MenuFileOpenCloudDig", "Directory"))
        self.pushButton_3.setText(_translate("MenuFileOpenCloudDig", "Search"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MenuFileOpenCloudDig = QtWidgets.QDialog()
    ui = Ui_MenuFileOpenCloudDig()
    ui.setupUi(MenuFileOpenCloudDig)
    MenuFileOpenCloudDig.show()
    sys.exit(app.exec_())
