# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'resources/settings_cloud_account_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MenuSettingsAccountDialog(object):
    def setupUi(self, MenuSettingsAccountDialog):
        MenuSettingsAccountDialog.setObjectName("MenuSettingsAccountDialog")
        MenuSettingsAccountDialog.resize(967, 624)
        self.account_info_widget_1 = QtWidgets.QWidget(MenuSettingsAccountDialog)
        self.account_info_widget_1.setGeometry(QtCore.QRect(9, 9, 951, 151))
        self.account_info_widget_1.setObjectName("account_info_widget_1")
        self.gridLayout = QtWidgets.QGridLayout(self.account_info_widget_1)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.container_name_textedit_1 = QtWidgets.QTextEdit(self.account_info_widget_1)
        self.container_name_textedit_1.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.container_name_textedit_1.sizePolicy().hasHeightForWidth())
        self.container_name_textedit_1.setSizePolicy(sizePolicy)
        self.container_name_textedit_1.setMaximumSize(QtCore.QSize(16777215, 25))
        self.container_name_textedit_1.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.container_name_textedit_1.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.container_name_textedit_1.setObjectName("container_name_textedit_1")
        self.gridLayout.addWidget(self.container_name_textedit_1, 3, 1, 1, 1)
        self.account_name_textedit_1 = QtWidgets.QTextEdit(self.account_info_widget_1)
        self.account_name_textedit_1.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.account_name_textedit_1.sizePolicy().hasHeightForWidth())
        self.account_name_textedit_1.setSizePolicy(sizePolicy)
        self.account_name_textedit_1.setMaximumSize(QtCore.QSize(16777215, 25))
        self.account_name_textedit_1.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.account_name_textedit_1.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.account_name_textedit_1.setReadOnly(False)
        self.account_name_textedit_1.setObjectName("account_name_textedit_1")
        self.gridLayout.addWidget(self.account_name_textedit_1, 1, 1, 1, 1)
        self.account_name_label_1 = QtWidgets.QLabel(self.account_info_widget_1)
        self.account_name_label_1.setObjectName("account_name_label_1")
        self.gridLayout.addWidget(self.account_name_label_1, 1, 0, 1, 1)
        self.container_name_label_1 = QtWidgets.QLabel(self.account_info_widget_1)
        self.container_name_label_1.setObjectName("container_name_label_1")
        self.gridLayout.addWidget(self.container_name_label_1, 3, 0, 1, 1)
        self.connection_str_label_1 = QtWidgets.QLabel(self.account_info_widget_1)
        self.connection_str_label_1.setObjectName("connection_str_label_1")
        self.gridLayout.addWidget(self.connection_str_label_1, 2, 0, 1, 1)
        self.connection_str_textedit_1 = QtWidgets.QTextEdit(self.account_info_widget_1)
        self.connection_str_textedit_1.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.connection_str_textedit_1.sizePolicy().hasHeightForWidth())
        self.connection_str_textedit_1.setSizePolicy(sizePolicy)
        self.connection_str_textedit_1.setMaximumSize(QtCore.QSize(16777215, 25))
        self.connection_str_textedit_1.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.connection_str_textedit_1.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.connection_str_textedit_1.setObjectName("connection_str_textedit_1")
        self.gridLayout.addWidget(self.connection_str_textedit_1, 2, 1, 1, 1)
        self.widget = QtWidgets.QWidget(self.account_info_widget_1)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label1 = QtWidgets.QLabel(self.widget)
        self.label1.setObjectName("label1")
        self.horizontalLayout.addWidget(self.label1)
        self.edit_pushButton_1 = QtWidgets.QPushButton(self.widget)
        self.edit_pushButton_1.setObjectName("edit_pushButton_1")
        self.horizontalLayout.addWidget(self.edit_pushButton_1)
        self.apply_pushButton_1 = QtWidgets.QPushButton(self.widget)
        self.apply_pushButton_1.setObjectName("apply_pushButton_1")
        self.horizontalLayout.addWidget(self.apply_pushButton_1)
        self.connectiontest_pushButton_1 = QtWidgets.QPushButton(self.widget)
        self.connectiontest_pushButton_1.setObjectName("connectiontest_pushButton_1")
        self.horizontalLayout.addWidget(self.connectiontest_pushButton_1)
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 2)

        self.retranslateUi(MenuSettingsAccountDialog)
        QtCore.QMetaObject.connectSlotsByName(MenuSettingsAccountDialog)

    def retranslateUi(self, MenuSettingsAccountDialog):
        _translate = QtCore.QCoreApplication.translate
        MenuSettingsAccountDialog.setWindowTitle(_translate("MenuSettingsAccountDialog", "Dialog"))
        self.account_name_label_1.setText(_translate("MenuSettingsAccountDialog", "account name"))
        self.container_name_label_1.setText(_translate("MenuSettingsAccountDialog", "container name"))
        self.connection_str_label_1.setText(_translate("MenuSettingsAccountDialog", "connection string"))
        self.label1.setText(_translate("MenuSettingsAccountDialog", "Account 1"))
        self.edit_pushButton_1.setText(_translate("MenuSettingsAccountDialog", "Edit"))
        self.apply_pushButton_1.setText(_translate("MenuSettingsAccountDialog", "Apply"))
        self.connectiontest_pushButton_1.setText(_translate("MenuSettingsAccountDialog", "Connection test"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MenuSettingsAccountDialog = QtWidgets.QDialog()
    ui = Ui_MenuSettingsAccountDialog()
    ui.setupUi(MenuSettingsAccountDialog)
    MenuSettingsAccountDialog.show()
    sys.exit(app.exec_())
